@startuml 

top to bottom direction

title <b><size:30>&#160;&#160; Class Diagram (Atomic Architecture) &#160;&#160;</size></b>

'-----------Main--------------

class Person{
    - id: String
    - firstName: String
    - lastName: String
    - email: String
    - address: String
    - createDate: DateTime
    - updateDate: DateTime
}


Class Landlord{}
interface ILandlordRepositiory{
    + login(int id) : Token
    + logout(int id): void
}

Landlord "1..1" *-- "1..n" Tenant       : > holds  
ILandlordRepositiory <|.right. Landlord : depend on


'Documents
abstract class AbstractDocumentTemplate {
    - id: Number
    - page: HTMLDocument
    - engine: Engine
}


interface IDocumentToolkit{
    + print(AbstractDocumentTemplate? template): void;
    'Static Method
    + generatePDFFromLayout(): PDFFile
    + buildTemplate(AbstractDocumentTemplate t) : statict Template
}


AbstractDocumentTemplate <|.. IDocumentToolkit

interface IDocumentTemplateRepository{
    add(Template template): void
}


IManagedRepository <|.right. IDocumentTemplateRepository: < implement
IDocumentTemplateRepository <|..  AbstractDocumentTemplate


class Report {
    - id: Number
    - title: String
    - description: String
    - file: CompressedFile
}

interface IReport{
    + add(Report report): void
}

IReport  <|.. Report : < depend on

IDocumentToolkit <|.. Report : < implement




'----------------------Tenants----------------

class Tenant {}


Person <|-up- Landlord
Person <|-- Tenant


class TenantGroup{
    - responsableId : int
    + generateBill(): void
}


interface ITenantGroupRepository{
    + add(TenantGroup group): void
    + dispatchBill(): void
}


IManagedRepository <|.. ITenantGroupRepository : < depend on
ITenantGroupRepository <|.. TenantGroup        : < depend on

Tenant "1..n" *-left- "1..1" TenantGroup : > compose



interface IManagedRepository {
    + getAll(): void
    + getById(int id): void
    + deleteById(int id): void
    + deleteAll(List<int>? ids): void
    + update(int id,List<String> keys, List<Object> values): void
    + getCount(int id, Periode? time): void
}



interface ITenantRepository{
    + add(Tenant tenant): void
}




ITenantRepository .up.|> IManagedRepository : depend on >
ITenantRepository <|.down. Tenant: < depend on


'---------Billings--------------------



class BankCard{
    - iban:         String    
    - bankName:     String
    - cardNumber:   Number
    - cardType:     String
    - expiryDate:   DateTime
    - currency:     DateTime
}


class Bill{
    - id: Number
    - amount: Number
    - createDate: DateTime
    - maturityDate: DateTime
}

Tenant "1..n" o-- "1..n" Bill: make >
Tenant "1..n"  *-down- "1..n" BankCard: > owns
Bill .left.|> IDocumentToolkit:  > implement

interface IBillRepository{
    + add(Bill bill): void
    + getRemainingAmout(): void
}


IManagedRepository <.. IBillRepository: < depend on
IBillRepository <|.left. Bill : < depend on


class RentReceipt{
    - paid: Number
    - date: DateTime
}


IDocumentToolkit <|.right. RentReceipt 
RentReceipt "1..n" -down-o "1..1" Bill : < create 
RentReceipt "1..n" --o "1..1" BankCard : is used by >


interface IRentReceiptInterface{}


IManagedRepository <|.right. IRentReceiptInterface : <depend on
IRentReceiptInterface <|.. RentReceipt : < depends on

    

Rent  .up.|> IDocumentToolkit : control < 


class Debts{
    - id: Number
    - label: String
    - amount: Number
    - description: String
}

Tenant "1..1" o-up- "1..n" Debts:  > has
Debts "1..1" -right-> "1..1" Bill: > relate to 


'----------------------Rents------------------------


class Rent{
    - montant: Number
    - type: RENTTYPE
    - createDate: DateTime
    - fillIn    : Number
    - lease     : File
    - start     : DateTime
    - end       : DateTime
    - endDate   : DateTime

    +generateLease(): File
}


Rent -- RENTTYPE : > contains 


interface IRentRepository{
    + sendViaEmail(Person id): void  
    + add(Rent rent): void
}


IRentRepository ..|> IManagedRepository: depends on >



enum RENTTYPE{
    INDIVIDUAL
    COLLECTIVE
}




IManagedRepository <|.. IReport : < depend on


Tenant "1..1"  -up- "1..1" Rent : hold > 
TenantGroup --o Rent : hold > 

Rent "1..1" o-right- "1..1" Report : create >
Rent .left.|> IRentRepository      : depend on >



'--------------------Apartements--------------------------


class Appartment{
    - id: Number
    - name: Number
    - location: String
    - rentFee: Number
    - inRepair: boolean
    - saleValue : Number
    - visibility: boolean
}


interface IAppartementRepository{
    + delegate(int id): void
    + saveContract(File file): void
    + incorporateAppartment(int id) : void
    + setInRepair(boolean bool): void
}


IManagedRepository  <|.left. IAppartementRepository: < depend on
IAppartementRepository <|.. Appartment : < depend on

Appartment "1..1" <-right- "1..1" Rent : has <
Appartment "0..n" <-up- "1..1" Landlord:  possesses/view




'--------------------------Buying/Selling------------------------



class Appointment{
    - id: Number
    - decription: String
    - date  : DateTime
    - activate : bool
    + createFormData(): FormData
    + changeState(): void 
}


interface IAppointmentRepository{
    + toogleAtivation(): void
    + add(FormData formaData): void
}



Appartment "1..1" o-up- "1..1" Appointment : < arranged on
Appointment .up.|> IAppointmentRepository: depond on >
IAppointmentRepository ..|> IManagedRepository :  depnd on >



'Graphs



enum ChartEnum{
    LINECHART
    AREACHART
    BARCHART
    PIRCHART
}

enum ChartMode{
    COMPARE
    SEPARATE
    MERGE
}


class Chart{
    - type: ChartEnum
    - mode: ChartMode
    + generateDataset(): ChartDataset
}

Chart -right- ChartEnum:  > contains
Chart -right- ChartMode:  > contains

Rent     "1..n" <-left-  "1..1" Chart : > generate
Bill "1..n" <-down-  "1..1" Chart : > generate
Report   "1..n" <-down-  "1..1" Chart :  generate <


class Prediction{
    - id: String
    - title: String
    - description
    - createDate: DateTime
    - updateDate: DateTime
}


interface IPredictionRepository{
    add(Prediction prediction): void
}

IManagedRepository <|.up. IPredictionRepository: < depend on 
IPredictionRepository <|.. Prediction : < depend on 

Chart "1..1" *-up- "0..1" Prediction: > associate



'--------------------2D/3D Graphics Models--------------------


class CompressedFile{
    - id: Number
    - url: String
    - name: String
    - file: File?
    + getUnZipFile(): File
}


class 3DModel{
    + stopAnimation(): void
    + launchOrbitAnimation(): void
    + discardFromScene(Scene scene): void
    + setFocusOnCursorPosition(Position coord) : void
    + setPostionRelativeTo(3DModel model): void
}



class Image{
    + getCroppedImage(int width, height, Position coord): void
    + blur(px pixel): void
    + filter(brightness, blur...)      : void
}



CompressedFile <|-down- 3DModel
CompressedFile <|-- Image


3DModel "0..n" <-up- "0..1" Appartment:   display <
Image  "0..n" <-right- "0..1"  Appartment:   display <


Tenant "1..1" --> "1..1" 3DModel : display
Tenant "1..1" --> "1..1" Image   : display



@enduml