
import type { Metadata } from "next";
import "./globals.css";


import AppContextProvider from "@/contexts/AppContextProvider";
import AppWrapper from "@/appWrapper/appWrapper";


export const metadata: Metadata = {
  title: "Immo",
  description: "Generated by create next app",
};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) {

  return (
    <html lang="en">
        <AppContextProvider>
            <AppWrapper>
                {children}
            </AppWrapper>
        </AppContextProvider>
    </html>
  );
}
