
import type { Metadata } from "next";
import "./globals.css";

import NavBar from "@/ui/navBar/navBar";
import SideBar from "@/ui/sidebar/sideBar"
import AppContextProvider, { useAppContext } from "@/contexts/AppContextProvider";
import AppWrapper from "@/layout/appWrapper";





export const metadata: Metadata = {
  title: "Immo flow",
  description: "Generated by create next app",
};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
        <AppContextProvider>
            <AppWrapper>
                {children}
            </AppWrapper>
        </AppContextProvider>
    </html>
  );
}
